### PR TITLE
Add PyData

### PR DESCRIPTION
**Pull request by janpipek**
Hi, after some discussion on Slack, I:

- Added a box for PyData
- Did not remove any other box (meaning broken grid)
- Did not add NumFOCUS as "We collaborate with..." (yet or ever - to be discussed)

I'd like Ondřej and Jakub to see this before a formal review.

Note: I have not tested the build, I was a bit lazy to do the setup (which does not work out of the box on my current Windows machine).

### CODE REVIEW

**Comment by janpipek** [comment]
@coobas @kokes

**Comment by coobas** [comment]
Looks very good to me 👍

**Review by honzajavorek — APPROVED** [review]
👍

**Comment by honzajavorek** [comment]
image

**Comment by janpipek** [comment]
image

Seems like a CSS caching problem to me.

**Comment by honzajavorek** [comment]
Yup you're right. And I'm sorry I deleted the comment, I thought nobody noticed yet.

**Pull request merged**
